watchlist: watchlists/popular.txt

filters:
  price_ceiling: 20.0
  rsi_threshold: 50
  volume_multiplier: 2.0
  market_cap_ceiling: 50000000000000
  float_ceiling: 1000000000000
  only_positive_macd: true

polygon:
  api_key: "YOUR_API_KEY_HERE"

alerts:
  default_email: "youremail@domain.com"
  brevo_key: "YOUR_BREVO_KEY_HERE"
  default_webhook: "YOUR_WEBHOOK_URL_HERE"